### ISSUE TITLE
Glitches 

### ISSUE THREAD

**Issue by drosenhoover** [batemanm/gamepad#2]
I love the code. It works like a charm most of the time. I am getting double hits on the right-right button and somewhere there is a glitch for the select which is exiting my game.. I have rebuilt the controller 3 different times using new material  and the same thing happens. Please help if more info is needed in would be glad to supply it

**Comment by batemanm** [comment]
After you've rebuilt the controller is it always the same buttons that you are having the issue with?

**Comment by drosenhoover** [comment]
Yes it is..I'm pretty sure it's the Right-right  button but I'll check here after a bit.

**Comment by drosenhoover** [comment]
I replaced  buttons, the hco5 bluetooth module and the arduino pro mini

**Comment by drosenhoover** [comment]
It is the right button..it is just on this controller. When I use my android device for the gamepad it works just fine

**Comment by drosenhoover** [comment]
I have got it to work. My baud rates on the code for both the controller and game was different same as the bluetooth devises. Sorry for accusing the code. It is awesome

**Comment by batemanm** [comment]
Glad you found the problem :-) I was looking through the code to see if there was anything I did that make it fail but I hadn't found anything sensible other than bit error on the serial line to the bluetooth module which is a soldering error but you said you'd rebuilt it already so that seemed unlikely.
